const organizations = [
  { id: 'demo', name: 'ChatterAI' },
  { id: 1, name: 'Another Space' },
];

const users = [
  { id: 'chatterai', first_name: 'Demo', last_name: 'ChatterAI', email: 'demo@demo.com', username: 'demo', avatar: 'https://www.gravatar.com/avatar/0000?s=200&d=robohash' },
  { id: 1, first_name: 'John', last_name: 'First', email: 'john@first.com', username: '', avatar: 'https://www.gravatar.com/avatar/1111?s=200&d=robohash' },
  { id: 2, first_name: 'Jane', last_name: 'Second', email: 'jane@second.com', username: '', avatar: 'https://www.gravatar.com/avatar/2222?s=200&d=robohash' },
  { id: 3, first_name: 'Joe', last_name: 'Third', email: 'joe@third.com', username: '', avatar: 'https://www.gravatar.com/avatar/3333?s=200&d=robohash' },
  { id: 4, first_name: 'Alice', last_name: 'Anderson', email: 'alice@anderson.com', username: '', avatar: 'https://www.gravatar.com/avatar/4444?s=200&d=robohash' },
  { id: 5, first_name: 'Bob', last_name: 'Baker', email: 'bob@baker.com', username: '', avatar: 'https://www.gravatar.com/avatar/5555?s=200&d=robohash' },
];

const user_organizations = [
  { user_id: 'chatterai', organization_id: 'demo'},
  { user_id: 1, organization_id: 'demo' },
  { user_id: 2, organization_id: 'demo' },
  { user_id: 3, organization_id: 'demo' },
  { user_id: 4, organization_id: 'demo' },
  { user_id: 5, organization_id: 'demo' },
];

const conversations = [
  { id: 1, name: 'Team Brainstorming', type: 'public', created_by: 1, organization_id: 'demo' },
  { id: 2, name: 'Project Updates', type: 'public', created_by: 2, organization_id: 'demo' },
  { id: 3, name: 'Weekend Discussion', type: 'public', created_by: 3, organization_id: 'demo' },
  { id: 4, name: 'Work-life Balance', type: 'private', created_by: 1, organization_id: 'demo' },
  { id: 5, name: 'Productivity Tips', type: 'private', created_by: 2, organization_id: 'demo' },
  { id: 6, name: 'Creative Mind Space', type: 'private', created_by: 3, organization_id: 'demo' },
  { id: 7, name: 'Mindfulness and Wellness', type: 'private', created_by: 'chatterai', organization_id: 'demo' },
  { id: 8, name: 'Professional Development', type: 'private', created_by: 'chatterai', organization_id: 'demo' },
  { id: 9, name: 'Book Club', type: 'private', created_by: 'chatterai', organization_id: 'demo' },
  { id: 10, name: 'Fitness and Health Goals', type: 'private', created_by: 'chatterai', organization_id: 'demo' },
  { id: 11, name: 'Culinary Corner', type: 'private', created_by: 'chatterai', organization_id: 'demo' },
  { id: 12, name: 'Travelogue', type: 'private', created_by: 'chatterai', organization_id: 'demo' },
  { id: 13, name: 'Tech Trends', type: 'public', created_by: 'chatterai', organization_id: 'demo' },
  { id: 14, name: 'Cultural Exchange', type: 'public', created_by: 'chatterai', organization_id: 'demo' },
  { id: 15, name: 'Social Events Hub', type: 'public', created_by: 1, organization_id: 'demo' },
];

const user_conversations = [
  { conversation_id: 1, user_id: 1 },
  { conversation_id: 1, user_id: 2 },
  { conversation_id: 2, user_id: 1 },
  { conversation_id: 2, user_id: 2 },
  { conversation_id: 2, user_id: 3 },
  { conversation_id: 3, user_id: 2 },
  { conversation_id: 3, user_id: 3 },
  { conversation_id: 4, user_id: 1 },
  { conversation_id: 5, user_id: 2 },
  { conversation_id: 6, user_id: 3 },
  { conversation_id: 7, user_id: 'chatterai' },
  { conversation_id: 8, user_id: 'chatterai' },
  { conversation_id: 9, user_id: 'chatterai' },
  { conversation_id: 10, user_id: 'chatterai' },
  { conversation_id: 11, user_id: 'chatterai' },
  { conversation_id: 12, user_id: 'chatterai' },
  { conversation_id: 13, user_id: 'chatterai' },
  { conversation_id: 14, user_id: 'chatterai' },
  { conversation_id: 15, user_id: 1 },
  { conversation_id: 4, user_id: 4 },
  { conversation_id: 5, user_id: 4 },
  { conversation_id: 6, user_id: 4 },
  { conversation_id: 5, user_id: 5 },
  { conversation_id: 6, user_id: 5 },
];

const messages = [
  { id: 1, conversation_id: 1, user_id: 1, content: 'Hi there, ChatGPT!' },
  { id: 2, conversation_id: 1, user_id: 'chatgpt', content: 'Hello, John!' },
  { id: 3, conversation_id: 1, user_id: 2, content: 'How are you?' },
  { id: 4, conversation_id: 1, user_id: 'chatgpt', content: 'I am doing well, thanks!' },
  { id: 5, conversation_id: 2, user_id: 2, content: 'Hi there, whoever is there!' },
  { id: 6, conversation_id: 2, user_id: 'chatgpt', content: 'Hello, Jane!' },
  { id: 7, conversation_id: 2, user_id: 2, content: 'What\'s new?' },
  { id: 8, conversation_id: 2, user_id: 'chatgpt', content: 'Not much, just chatting away with everyone! Apparently...' },
  { id: 9, conversation_id: 2, user_id: 3, content: 'Well that\'s boring...' },
  { id: 10, conversation_id: 2, user_id: 'chatgpt', content: 'I know, right?' },
  { id: 11, conversation_id: 3, user_id: 3, content: 'Hi there, ChatGPT!' },
  { id: 12, conversation_id: 3, user_id: 'chatgpt', content: 'Hello, Joe!' },
  { id: 13, conversation_id: 3, user_id: 2, content: 'What have you done recently?' },
  { id: 14, conversation_id: 3, user_id: 'chatgpt', content: 'I have been working on a secret project!' },
  { id: 15, conversation_id: 4, user_id: 1, content: 'Hi there, ChatGPT!' },
  { id: 16, conversation_id: 4, user_id: 'chatgpt', content: 'Hello, John!' },
  { id: 17, conversation_id: 5, user_id: 2, content: 'Hi there, ChatGPT!' },
  { id: 18, conversation_id: 5, user_id: 'chatgpt', content: 'Hello, Jane!' },
  { id: 19, conversation_id: 6, user_id: 3, content: 'Hi there, ChatGPT!' },
  { id: 20, conversation_id: 6, user_id: 'chatgpt', content: 'Hello, Joe!' },
  { id: 21, conversation_id: 7, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 22, conversation_id: 7, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 23, conversation_id: 8, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 24, conversation_id: 8, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 25, conversation_id: 9, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 26, conversation_id: 9, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 27, conversation_id: 10, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 28, conversation_id: 10, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 29, conversation_id: 11, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 30, conversation_id: 11, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 31, conversation_id: 12, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 32, conversation_id: 12, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 33, conversation_id: 13, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 34, conversation_id: 13, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 35, conversation_id: 14, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 36, conversation_id: 14, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 37, conversation_id: 15, user_id: 'chatterai', content: 'Hi there, ChatGPT!' },
  { id: 38, conversation_id: 15, user_id: 'chatgpt', content: 'Hello, chatterai!' },
  { id: 39, conversation_id: 4, user_id: 4, content: 'Hey, John! How\'s it going?' },
  { id: 40, conversation_id: 4, user_id: 1, content: 'Hey, Alice! I\'m doing great. How about you?' },
  { id: 41, conversation_id: 5, user_id: 5, content: 'Hello, ChatGPT! Nice to meet you all!' },
  { id: 42, conversation_id: 5, user_id: 'chatgpt', content: 'Hi, Bob! Welcome to the chat!' },
];

const data = {
  organizations,
  users,
  user_organizations,
  conversations,
  user_conversations,
  messages,
};

export default data;
